### PR TITLE
Updated lexLisp.hs for current version

### PR DESCRIPTION
**Pull request by sheganinans**

### CODE REVIEW

**Comment by sheganinans** [comment]
I still get a whole bunch of warnings, I don't know if you would want all the signatures added on, as well as some other stuff that is redundant that I didn't remove:
Text/Luthor/Indent.hs:209:13-14: Warning: …
    This binding for ‘s'’ shadows the existing binding
      bound at Text/Luthor/Indent.hs:204:9
Text/Luthor/Indent.hs:208:13: Warning: …
    This binding for ‘s’ shadows the existing binding
      bound at Text/Luthor/Indent.hs:202:9
Text/Luthor/Indent.hs:208:10: Warning: …
    This binding for ‘u’ shadows the existing binding
      bound at Text/Luthor/Indent.hs:202:6
Text/Luthor/Indent.hs:(201,1)-(211,21): Warning: …
    Top-level binding with no type signature:
      _withIndentationSet :: forall b
                                    s
                                    (m :: \* -> *)
                                    t
                                    s1
                                    u
                                    (m1 :: \* -> *).
                             Monad m =>
                             Bool
                             -> ParsecT s (t, IndentState s1 u m1) m b
                             -> ParsecT s (t, IndentState s1 u m1) m b
Text/Luthor/Syntax.hs:635:10-68: Warning: …
    Orphan instance:
      instance (IsString a, Stream s m Char) =>
               IsString (ParsecT s u m a)
Text/Luthor/Syntax.hs:660:45-48: Warning: …
    Defaulting the following constraint(s) to type ‘Integer’
      (Num b0)
        arising from a use of ‘impl’ at Text/Luthor/Syntax.hs:660:45-48
      (Integral b0)
        arising from a use of ‘fromIntegral’
        at Text/Luthor/Syntax.hs:660:24-35
    In the first argument of ‘foldl’, namely ‘impl’
    In the second argument of ‘(.)’, namely ‘foldl impl 0’
    In the expression: fromIntegral . foldl impl 0
Text/Luthor/Syntax.hs:644:1-43: Warning: …
    Top-level binding with no type signature:
      _asciiControl :: Char -> Bool
Text/Luthor/Syntax.hs:643:1-34: Warning: …
    Top-level binding with no type signature: _alphaNum :: Char -> Bool
Text/Luthor/Syntax.hs:642:1-31: Warning: …
    Top-level binding with no type signature: _digit :: Char -> Bool
Text/Luthor/Syntax.hs:641:1-35: Warning: …
    Top-level binding with no type signature: _alpha :: Char -> Bool
Text/Luthor/Syntax.hs:640:1-33: Warning: …
    Top-level binding with no type signature: _loAlpha :: Char -> Bool
Text/Luthor/Syntax.hs:639:1-33: Warning: …
    Top-level binding with no type signature: _upAlpha :: Char -> Bool
Text/Luthor/Syntax.hs:515:33-37: Warning: …
    Defaulting the following constraint(s) to type ‘String’
      (IsString a0) arising from the literal ‘"\&"’
    In the first argument of ‘void’, namely ‘"\&"’
    In the first argument of ‘(<|>)’, namely ‘void "\&"’
    In the second argument of ‘($)’, namely ‘void "\&" <|> bsnlwsbs’
Text/Luthor/Syntax.hs:488:22-25: Warning: …
    Defaulting the following constraint(s) to type ‘String’
      (IsString b0) arising from the literal ‘"''"’
    In the second argument of ‘(<$)’, namely ‘"''"’
    In the expression: '\'' <$ "''"
    In an equation for ‘escape’: escape = '\'' <$ "''"
Text/Luthor/Syntax.hs:411:12-23: Warning: …
    Defaulting the following constraint(s) to type ‘Integer’
      (Integral b0) arising from a use of ‘fromIntegral’
    In the first argument of ‘(.)’, namely ‘fromIntegral’
    In the first argument of ‘(<$>)’, namely
      ‘fromIntegral . stringToInteger 16’
    In the expression:
      fromIntegral . stringToInteger 16 <$> count 2 P.hexDigit
Text/Luthor/Syntax.hs:401:5-12: Warning: …
    This binding for ‘exponent’ shadows the existing binding
      imported from ‘Prelude’ at Text/Luthor/Syntax.hs:7:8-25
      (and originally defined in ‘GHC.Float’)
Text/Luthor/Syntax.hs:261:1-12: Warning: …
    Defined but not used: ‘lexDentation’
Text/Luthor/Syntax.hs:202:29-34: Warning: …
    Defaulting the following constraint(s) to type ‘String’
      (IsString a0) arising from the literal ‘"\r"’
    In the first argument of ‘void’, namely ‘"\r"’
    In the second argument of ‘($)’, namely ‘void "\r"’
    In the expression: expect "CRLF" $ void "\r"
Text/Luthor/Syntax.hs:65:1-54: Warning: …
    The import of ‘noneOf’ from module ‘Text.Parsec.Char’ is redundant

Haven't ran hlint on anything yet, so who knows?

**Comment by Zankoku-Okuno** [comment]
Whooo, it's been a while since I was committing code...

In any case, it seems straightforward to merge, though I'll take a closer look at this tonight, since I saw a couple of surprises.

**Comment by Zankoku-Okuno** [comment]
Now that I remember what's going on, I just wanted to mention:
lexing is broken with indentation-sensitive parsers, so lexLisp.hs still fails (although it compiles) on `docs/foo.l`.
I've opened an issue for this in https://github.com/Zankoku-Okuno/luthor/issues/2, but I'm currently head-down working on my thesis, so I probably won't get to it very soon.

**Comment by sheganinans** [comment]
Great! Hmm, I'll take a look at #2, but no promises. Thanks!

**Pull request merged**
